#pragma once

#define RENDERER_MAX_DESCRIPTOR_SETS 4096
#define RENDERER_MAX_UNIFORM_BUFFER_DESCRIPTORS 4096
#define RENDERER_MAX_SAMPLER_DESCRIPTORS 2048
#define MINIMUM_INTENSITY (5.0f / 256.0f)
#define INVERSE_MININUM_INTENSITY (1.0f / MINIMUM_INTENSITY)

#define TEST_LIGHT_COUNT 100
#define TEST_LIGHT_RANGE 25.0f