#pragma once

#define INDEX(x) static_cast<uint32_t>(x)

enum TextureSlot
{
	SLOT_DIFFUSE,
	SLOT_SPECULAR,
	SLOT_NORMALS,
	SLOT_ENVIRONMENT,
    SLOT_SHADOW_MAP,
	//SLOT_METALLIC,
    //SLOT_ROUGHNESS,
	SLOT_COUNT
};

enum ActorDescriptor
{
	AD_UNIFORM_BUFFER,
	AD_TEXTURE_DIFFUSE,
	AD_TEXTURE_SPECULAR,
	AD_TEXTURE_NORMALS,
	AD_TEXTURE_ENVIRONMENT,
    AD_TEXTURE_SHADOW_MAP,
    //AD_TEXTURE_METALLIC,
    //AD_TEXTURE_ROUGHENSS,
	AD_COUNT
};

enum DeferredDescriptor
{
	DD_TEXTURE_POSITION,
	DD_TEXTURE_NORMAL,
	DD_TEXTURE_COLOR,
	DD_TEXTURE_SPECULAR,
    DD_TEXTURE_METALLIC,
    DD_TEXTURE_ROUGHNESS,
    DD_TEXTURE_SHADOW_MAP,
	DD_TEXTURE_IRRADIANCE_MAP,
	DD_COUNT
};

enum LightDescriptor
{
	LD_UNIFORM_BUFFER,
	LD_COUNT
};

enum LightPassSetIndices
{
	LPS_GBUFFER_TEXTURES,
	LPS_LIGHT_DATA,
	LPS_COUNT
};

enum GBufferIndex
{
	GB_POSITION,
	GB_NORMAL,
	GB_COLOR,
	GB_SPECULAR,
    GB_METALLIC,
    GB_ROUGHNESS,
	GB_COUNT
};

enum Attachments
{
	ATTACHMENT_BACK,
	ATTACHMENT_DEPTH,
	ATTACHMENT_GBUFFER_POSITION,
	ATTACHMENT_GBUFFER_NORMAL,
	ATTACHMENT_GBUFFER_COLOR,
	ATTACHMENT_GBUFFER_SPECULAR,
    ATTACHMENT_GBUFFER_METALLIC,
    ATTACHMENT_GBUFFER_ROUGHNESS,
	ATTACHMENT_LIT_COLOR,
	ATTACHMENT_COUNT
};

enum SubPasses
{
	PASS_DEPTH = 0,
	PASS_GEOMETRY = 1,
	PASS_DEFERRED = 2,
    PASS_POST_PROCESS = 3
};

enum class ProjectionMode
{
	ORTHOGRAPHIC,
	PERSPECTIVE
};

enum DebugMode
{
	DEBUG_NONE,
	DEBUG_GBUFFER,
	DEBUG_ENVIRONMENT_CAPTURE,
	DEBUG_SHADOW_MAP
};